"""
scan_ai_residues.py
~~~~~~~~~~~~~~~~~~~~

This module implements a simple command‑line utility that inspects an input
document for a handful of tell‑tale artefacts that can arise when AI tools
are used without careful editing. The goal is to help researchers and
editors spot phrases that are clearly out of place, such as leftover AI
prompts, placeholders like "TBD", bad optical character recognition (OCR)
glue, boilerplate clichés, broken citations, and weasel phrases lacking
sources. It does **not** attempt to infer whether a document was produced
by AI; instead, it highlights text that deserves a closer look.

To use this script, run it on a plain‑text document. For example:

    python scan_ai_residues.py --input input.txt --output result.json

The resulting JSON follows the schema described in the conversation:

```
{
  "meta": {
    "lang": "en",
    "chars": <int>,
    "sentences": <int>,
    "runtime_ms": <float>
  },
  "summary": {
    "total_flags": <int>,
    "by_category": {
      "ai_prompt_residue": <int>,
      "placeholders": <int>,
      "ocr_artifacts": <int>,
      "boilerplate": <int>,
      "citation_anomalies": <int>,
      "fabrication_markers": <int>
    },
    "hotspots_sentence_indexes": [<int>, ...]
  },
  "flags": [
    {
      "category": "ai_prompt_residue|placeholders|ocr_artifacts|boilerplate|citation_anomalies|fabrication_markers",
      "span": {"start": <int>, "end": <int>, "sentence_index": <int>},
      "text": "<snippet>",
      "evidence": {
        "pattern": "<regex_name>",
        "notes": "<why it was flagged>"
      },
      "severity": "low|medium|high",
      "suggested_fix": "<suggestion>"
    }, ...
  ],
  "recommendations": [
    {"message": "<summary message>", "fix": "<general advice>", "priority": "low|medium|high"}, ...
  ]
}
```

The script performs a deterministic scan based on regular expressions and
simple heuristics. It splits the document into sentences using a naive
period/semicolon/colon/newline delimiter, then applies category‑specific
regexes to the entire document. Each match is mapped back to the
appropriate sentence index and recorded. Hotspot sentences are those with
more than one flag. The "severity" field is assigned based on the
category: clear AI instructions or OCR corruption are high; clichés and
weasel phrases are medium; minor placeholders are low.

This utility is deliberately lightweight. It does not depend on external
libraries beyond Python's standard library. It should run on modest
hardware and produce JSON that can be consumed by downstream tools or
rendered in a user interface.
"""

import argparse
import json
import re
import time
from typing import Dict, List, Tuple


def split_sentences(text: str) -> Tuple[List[str], List[Tuple[int, int]]]:
    """Split text into sentences and return both the sentence list and
    character spans for each sentence.
    """
    sentences: List[str] = []
    spans: List[Tuple[int, int]] = []
    start = 0
    delim_pattern = re.compile(r"(?<=[.!?])\s+|\n+")
    for match in delim_pattern.finditer(text):
        end = match.start()
        if end > start:
            sentences.append(text[start:end].strip())
            spans.append((start, end))
        start = match.end()
    if start < len(text):
        sentences.append(text[start:].strip())
        spans.append((start, len(text)))
    return sentences, spans


class ZenithEngine:
    """Zenith v26.1 Institutional Standard (IS-v26) Engine.
    Automates the Domain-Handshake Linker (DHL) protocol.
    """
    def __init__(self):
        self.institutional_seed = 2142086823
        self.z_pillar_dna = "CCTGTGACTGTGGGGTTCACGCTCCCGGGTG"
        self.z_pillar_dna_rev = "CACCCGGGAGCGTGAACCCCACAGTCACAGG"
        self.linker_extension = 15

    def refine(self, full_sequence: str, start: int, end: int) -> str:
        s = max(0, start - self.linker_extension - 1)
        e = min(len(full_sequence), end + self.linker_extension)
        return full_sequence[s:e]


class PatternBank:
    """Holds compiled regular expressions for various artifact categories.

    Patterns are case‑insensitive and include explanatory names. The
    keys of the `patterns` dictionary correspond to category names and
    values are lists of (name, regex) tuples. Adding patterns in one
    place makes it easy to tune the scanner.
    """

    def __init__(self) -> None:
        flags = re.IGNORECASE | re.MULTILINE
        self.patterns: Dict[str, List[Tuple[str, re.Pattern]]] = {
            "ai_prompt_residue": [
                (
                    "ai_meta_text",
                    re.compile(
                        r"\b(as an ai|i am an ai|ai mode|the following (is|was) (an )?abstract generated by ai)\b",
                        flags,
                    ),
                ),
                (
                    "prompt_instruction",
                    re.compile(
                        r"\b(please rephrase|rewrite the following|make it more professional|act as (an?|the))\b",
                        flags,
                    ),
                ),
            ],
            "placeholders": [
                (
                    "todo_placeholder",
                    re.compile(
                        r"\b(TBD|to be determined|lorem ipsum)\b|\[\[(note|todo):[^\]]+\]\]",
                        flags,
                    ),
                ),
                (
                    "insert_placeholder",
                    re.compile(
                        r"\[(insert (figure|table|image)[^\]]*)\]|\bXX%\b|\bREF\b",
                        flags,
                    ),
                ),
            ],
            "ocr_artifacts": [
                (
                    "hyphen_split",
                    re.compile(r"[A-Za-z]{2,}-\s+[A-Za-z]{2,}", flags),
                ),
                (
                    "header_footer_bleed",
                    re.compile(
                        r"\b(page|figure|table)\s+\d+\b.*\b(preprint|copyright|received)\b",
                        flags,
                    ),
                ),
                (
                    "improbable_bigram",
                    re.compile(
                        r"vegetative electron microscopy|granule clusters nuclei",
                        flags,
                    ),
                ),
            ],
            "boilerplate": [
                (
                    "cliche_academic",
                    re.compile(
                        r"\b(it is worth noting that|in today'?s world|plays a (crucial|significant) role|at the end of the day|this study makes a (significant|valuable) contribution)\b",
                        flags,
                    ),
                ),
            ],
            "citation_anomalies": [
                (
                    "orphan_tag",
                    re.compile(r"\((?:et al\.|\d{4})\)", flags),
                ),
                (
                    "broken_doi",
                    re.compile(r"10\.\d{3,9}/[\w\-_.]+[^\w/\-_.]", flags),
                ),
                (
                    "bracket_artifact",
                    re.compile(r"\[(ai\-generated text|please rephrase)[^\]]*\]", flags),
                ),
            ],
            "fabrication_markers": [
                (
                    "weasel_no_cite",
                    re.compile(
                        r"\b(according to research|many studies have shown|researchers say|it is widely believed)\b",
                        flags,
                    ),
                ),
            ],
            "zenith_reprogramming": [
                (
                    "cardiac_factor",
                    re.compile(r"\b(GATA4|TBX5|NKX2\.5)\b", flags),
                ),
                (
                    "yamanaka_factor",
                    re.compile(r"\b(OCT4|SOX2|KLF4|MYC)\b", flags),
                ),
            ],
        }


def scan_document(
    document: str, max_flags: int = 400
) -> Dict[str, object]:
    """Scan the input document for artefacts and return a structured JSON.

    Args:
        document: The full document as a single string.
        max_flags: The maximum number of individual flags to emit. Excess
            matches are truncated but still counted in summaries.

    Returns:
        A dictionary matching the required JSON schema.
    """
    start_time = time.perf_counter()
    # Normalise newline characters
    text = document.replace("\r\n", "\n")
    chars = len(text)
    # Split into sentences and map offsets
    sentences, sentence_spans = split_sentences(text)
    num_sentences = len(sentences)

    pattern_bank = PatternBank()

    flags_out: List[Dict[str, object]] = []
    category_counts = {
        "ai_prompt_residue": 0,
        "placeholders": 0,
        "ocr_artifacts": 0,
        "boilerplate": 0,
        "citation_anomalies": 0,
        "fabrication_markers": 0,
        "zenith_reprogramming": 0,
    }

    # Helper to determine severity by category
    severity_map = {
        "ai_prompt_residue": "high",
        "ocr_artifacts": "high",
        "citation_anomalies": "high",
        "boilerplate": "medium",
        "fabrication_markers": "medium",
        "placeholders": "low",
    }

    # Track counts per sentence index for hotspots
    sentence_flag_counts: Dict[int, int] = {}

    # Iterate over categories and patterns
    for category, pattern_list in pattern_bank.patterns.items():
        for name, regex in pattern_list:
            for match in regex.finditer(text):
                span_start, span_end = match.span()
                matched_text = text[span_start:span_end]
                # Determine sentence index
                # Use binary search over sentence_spans
                sentence_index = 0
                # Precomputed sentinel; linear search is fine for moderate document size
                for idx, (s_start, s_end) in enumerate(sentence_spans):
                    if s_start <= span_start < s_end:
                        sentence_index = idx
                        break
                # Increment counts
                category_counts[category] += 1
                sentence_flag_counts[sentence_index] = sentence_flag_counts.get(
                    sentence_index, 0
                ) + 1
                # Only collect up to max_flags for output
                if len(flags_out) < max_flags:
                    # Determine suggested fix and notes based on category/name
                    if category == "ai_prompt_residue":
                        suggested = "Delete AI meta/prompt text or rewrite as final prose."
                        notes = (
                            "explicit AI meta language"
                            if name == "ai_meta_text"
                            else "author instruction left in"
                        )
                    elif category == "placeholders":
                        suggested = "Fill in missing content or remove placeholder."
                        notes = "placeholder or editor note"
                    elif category == "ocr_artifacts":
                        if name == "hyphen_split":
                            suggested = "Remove newline hyphenation and join words correctly."
                            notes = "hyphenated word split across lines"
                        elif name == "header_footer_bleed":
                            suggested = "Remove page header/footer content from the body."
                            notes = "header/footer mixed with text"
                        else:
                            suggested = "Verify source and correct improbable terms."
                            notes = "improbable bigram or mis‑scan"
                    elif category == "boilerplate":
                        suggested = "Replace cliché with a concrete claim."
                        notes = "high‑frequency boilerplate"
                    elif category == "citation_anomalies":
                        if name == "orphan_tag":
                            suggested = "Ensure each citation has a corresponding reference entry."
                            notes = "citation tag without matching reference"
                        elif name == "broken_doi":
                            suggested = "Fix the DOI formatting or remove trailing junk."
                            notes = "malformed DOI"
                        else:
                            suggested = "Delete bracketed AI instructions or replace with proper citation."
                            notes = "bracketed AI artefact"
                    else:  # fabrication_markers
                        suggested = "Add a specific citation or rewrite as an observation."
                        notes = "weasel phrase without evidence"

                    flags_out.append(
                        {
                            "category": category,
                            "span": {
                                "start": span_start,
                                "end": span_end,
                                "sentence_index": sentence_index,
                            },
                            "text": matched_text,
                            "evidence": {"pattern": name, "notes": notes},
                            "severity": severity_map[category],
                            "suggested_fix": suggested,
                        }
                    )

    # Determine hotspots: sentences with more than one flag
    # Sort by descending flag counts; include up to 10 indexes
    hotspots = sorted(
        [idx for idx, count in sentence_flag_counts.items() if count > 1],
        key=lambda i: (-sentence_flag_counts[i], i),
    )[:10]

    total_flags = sum(category_counts.values())
    runtime_ms = (time.perf_counter() - start_time) * 1000

    # Build recommendations based on categories flagged
    recommendations: List[Dict[str, str]] = []
    if category_counts["ai_prompt_residue"] > 0:
        recommendations.append(
            {
                "message": "Remove AI or prompt meta language from the document.",
                "fix": "Delete lines mentioning AI generation or editing instructions.",
                "priority": "high",
            }
        )
    if category_counts["boilerplate"] > 0:
        recommendations.append(
            {
                "message": "Replace boilerplate phrases with concrete statements.",
                "fix": "Identify clichés and rewrite them with specific contributions or data.",
                "priority": "medium",
            }
        )
    if category_counts["ocr_artifacts"] > 0:
        recommendations.append(
            {
                "message": "Audit the document for OCR errors or column merges.",
                "fix": "Compare to the original source to correct mis‑joined words or terms.",
                "priority": "high",
            }
        )
    if category_counts["citation_anomalies"] > 0:
        recommendations.append(
            {
                "message": "Check citations and references for consistency.",
                "fix": "Ensure each in‑text citation has a reference and DOIs are correctly formatted.",
                "priority": "high",
            }
        )
    if category_counts["fabrication_markers"] > 0:
        recommendations.append(
            {
                "message": "Avoid weasel phrases without evidence.",
                "fix": "Cite specific studies or present data instead of vague claims.",
                "priority": "medium",
            }
        )
    if category_counts["placeholders"] > 0:
        recommendations.append(
            {
                "message": "Fill in all placeholders and editor notes before submission.",
                "fix": "Replace placeholders with real content or remove them entirely.",
                "priority": "low",
            }
        )

    result = {
        "meta": {
            "lang": "en",
            "chars": chars,
            "sentences": num_sentences,
            "runtime_ms": round(runtime_ms, 2),
        },
        "summary": {
            "total_flags": total_flags,
            "by_category": category_counts,
            "hotspots_sentence_indexes": hotspots,
        },
        "flags": flags_out,
        "recommendations": recommendations,
    }

    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Scan a text document for AI prompt residue, placeholders, OCR artefacts, clichés and citation anomalies.",
    )
    parser.add_argument(
        "--input", required=True, help="Path to input text file. Use '-' to read from stdin."
    )
    parser.add_argument(
        "--output", required=False, help="Path to output JSON file. Prints to stdout if omitted."
    )
    parser.add_argument(
        "--max_flags",
        type=int,
        default=400,
        help="Maximum number of flagged matches to include in the output (default 400).",
    )
    args = parser.parse_args()

    # Read input
    if args.input == "-":
        document = sys.stdin.read()
    else:
        with open(args.input, "r", encoding="utf-8") as f:
            document = f.read()

    result = scan_document(document, max_flags=args.max_flags)

    output_text = json.dumps(result, ensure_ascii=False, indent=2)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output_text)
    else:
        print(output_text)


if __name__ == "__main__":
    import sys

    main()